Making hw 1
shevvvo/homework_c pull request #2
Opened 2021-10-11 20:33 UTC by shevvvo

2021-10-12 18:46 UTC, poofik33 requested changes
Я не знаю как так получилось, но изменения в PR видны только частями, видимо что-то в main было до того, как был сделан PR, писал как смог. Не обессудь.

2021-10-12 18:46 UTC, poofik33 commented on project/minor_matrix.c
> +            } else if (i == index_i) {
Зачем условие если действия нет?

2021-10-12 18:46 UTC, poofik33 commented on project/minor_matrix.c
> +}
А почему 0 индексы i и j - это ошибочные случаи если отсчет в массиве идет от 0, ты даже в мейне специально понижаешь входные значения для этого. Вот проверить на то что индексы больше чем размер матрицы - этого нет

2021-10-12 18:46 UTC, poofik33 commented on project/main.c
> +}
1. Дефайны надо после инклюдов поставить.
2. Выводы ошибок - в stderr через fprintf (касается всего проекта)
3. Последи за форматированием проекта - отступы и пропуски пусть будут приведены в порядок, в main точно вижу 3 пропуска на 15-17

2021-10-12 20:43 UTC, poofik33 approved these changes
Замечаний не имею

2021-10-17 11:06 UTC, leshiy1295 requested changes
большая часть кода либо скопирована с подготовительной программы, либо находится не в основной ветке
подавляющее количество требований не выполнено
штраф 50%

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.c
> +void free_memory(int **matrix, size_t rows) {
почему int?

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.c
> +    for (size_t i = 0; i < rows; ++i) {
вектор векторов != матрица

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.c
> +        free(matrix[i]);
matrix может быть NULL

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.c
> +        fprintf(stderr, "Memory error new matrix");
функция работы с памятью не должна ничего выводить
максимум, что в её силах - вернуть код ошибки

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.c
> +        free(new_matrix);
зачем делать free, если указатель NULL??

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.c
> +            return NULL;
делали бы матрицу, а не вектор векторов - обошлись бы без return внутри цикла

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.c
> +    int **new_matrix = init_memory(rows - 1, cols - 1);
если cols/rows равны 1, то сюда передаются нули, что приведёт к ошибке, хотя формально это не ошибка, и решение существует

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.c
> +    size_t flag_j = 0;
использовать для флагов size_t - слишком затратно

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.c
> +        if (i != index_i) {
else?

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.c
> +                    flag_j++;
почему индексы называются флагами - непонятно

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.c
> +                    new_matrix[i - flag_i][j - flag_j] = matrix[i][j];
что делается в этой функции - непонятно
почему из индекса вычитаются флаги?

2021-10-17 11:06 UTC, leshiy1295 commented on project/minor_matrix.h
> +int **finding_minor(int **matrix, size_t rows, size_t cols, size_t index_i, size_t index_j);
const?

2022-03-03 21:50 UTC, closed without merging